name: hexlet-check
on: 
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"        
      - name: Run linter # Run Linter
      run: make lint



